version: "3"
services:
    fluxo-caixa-frontend:
        container_name: fluxo-caixa-frontend
        image: fluxo-caixa-frontend:latest
        ports:
            - 3000:80
        restart: always
        environment:
            - PRODUCTION=false
            - API_URL=http://cloudtecnologia.dynns.com:8001
            - TOKEN_URL=http://cloudtecnologia.dynns.com:8180/realms/CLOUD_TECNOLOGIA/protocol/openid-connect/token
            - VERSAO='v_23.11.2023'
            - CLI_ID=fluxo-caixa-client
            - CLI_SECRET=q80HxrDVjoX93hdA81g3JI4L61FUO2T9
