version: "3"
services:
    suporte-quarkus-backend:
        container_name: fluxo-caixa-frontend
        image: fluxo-caixa-frontend:lts
        ports:
            - 3000:80
        restart: always
        environment:
            - PRODUCTION=false
            - API_URL=http://cloudtecnologia.dynns.com:8085
            - TOKEN_URL=http://cloudtecnologia.dynns.com:8180/realms/CLOUD_TECNOLOGIA/protocol/openid-connect/token
            - VERSAO='v_14.07.2023'
            - CLI_ID=fluxo-caixa-client
            - CLI_SECRET=eSuHAFIQVlybVs5Mnr6lDbnovxmWeEcM
